// AUTO-GENERATED by mine_chemistry_claims.js — do not edit by hand.
//
// CHEMISTRY_CLAIMS: pair-level chemistry phrases mined from 17K hand-written
// pairing notes. Indexed by [drinkFlavor][foodFlavor] → { clause, count }.
// Engine consults at composition time when (flavor-set × flavor-set) match.
// ─────────────────────────────────────────────────────────────────────────────
const CHEMISTRY_CLAIMS = {
  "juniper": {
    "butter": {
      "clause": "the juniper cuts the butter",
      "count": 6
    }
  },
  "citrus": {
    "floral": {
      "clause": "the citrus meets the floral",
      "count": 8
    },
    "char": {
      "clause": "the citrus cuts the char",
      "count": 6
    },
    "vanilla": {
      "clause": "the citrus meets the vanilla",
      "count": 8
    }
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CHEMISTRY_CLAIMS };
} else if (typeof window !== 'undefined') {
  window.CHEMISTRY_CLAIMS = CHEMISTRY_CLAIMS;
}
