// AUTO-GENERATED by engine/mine_bottle_profiles.js -- do not edit by hand.
const BOTTLE_PROFILES_MINED = {
  "1881 Napa Valley": {
    tastingNotes: ["entry-point Napa Cab with dark cherry","blackcurrant","mocha","smooth medium tannin"],
    verdictHook: "big red",
  },
  "Aberlour 16": {
    character: "ex-bourbon + Oloroso Speyside",
    verdictHook: "Speyside scotch",
  },
  "Alexander Valley Chardonnay": {
    tastingNotes: ["Sonoma with ripe apple","pear","warm vanilla oak","smooth texture"],
    verdictHook: "Chardonnay",
  },
  "Amaro Nonino": {
    tastingNotes: ["grappa-based Friulian amaro","elegant and lighter than Averna"],
    verdictHook: "aperitivo",
  },
  "Aperol": {
    character: "orange marries the cinnamon",
    verdictHook: "aperitivo",
  },
  "Austin Hope Cabernet Sauvignon": {
    tastingNotes: ["Paso Robles Cab with ripe plum","dark cherry","mocha","warm spice"],
    verdictHook: "Napa Cab",
  },
  "Avion 44": {
    character: "Avion's 44-month aged extra añejo",
    verdictHook: "aged tequila",
  },
  "Balvenie 16 Single Barrel": {
    character: "First Fill American Oak",
    verdictHook: "Speyside scotch",
  },
  "Balvenie 21 Portwood": {
    tastingNotes: ["21yr Speyside finished in port casks","red-berry-fruit and port-richness","ultra-premium collector-register"],
    character: "ultra-premium 21yr port-cask Speyside",
    verdictHook: "Speyside scotch",
  },
  "Bardstown Foursquare": {
    character: "rum-cask + cocoa is textbook — tropical-rum + chocolate",
    verdictHook: "bourbon",
  },
  "Basil Hayden's": {
    character: "light high-rye and cocoa",
    verdictHook: "bourbon",
  },
  "Basil Hayden's 10 Year": {
    character: "aged oak and rye spice",
    verdictHook: "bourbon",
  },
  "Basil Hayden's Red Wine Cask": {
    tastingNotes: ["high-rye mash bill base","80-proof softer approach"],
    character: "BH high-rye red-wine finish",
    verdictHook: "bourbon",
  },
  "Basil Hayden's Toast": {
    character: "toast-barrel caramel and light high-rye",
    verdictHook: "bourbon",
  },
  "Belvedere Vodka": {
    tastingNotes: ["Polish rye-based vodka","premium clean-slightly-sweet profile"],
    verdictHook: "vodka",
  },
  "Blood Oath Pact 9": {
    character: "Pact 9 wine-cask blend",
    verdictHook: "bourbon",
  },
  "Booker's": {
    character: "Beam cask-strength 125-130 proof",
    verdictHook: "cask-strength bourbon",
  },
  "Bowdie's Old Fashioned": {
    character: "weight and vanilla-caramel depth",
    verdictHook: "spirit-forward cocktail",
  },
  "Bowmore 12": {
    character: "gentle peat and honey",
    verdictHook: "Islay scotch",
  },
  "Bruichladdich": {
    character: "clean barley notes and soft citrus",
    verdictHook: "Islay scotch",
  },
  "Buffalo Trace": {
    character: "BT's oak and vanilla",
    verdictHook: "bourbon",
  },
  "Bulleit Bourbon": {
    character: "90-proof high-rye with distinctive bold spice",
    verdictHook: "bourbon",
  },
  "Campari": {
    character: "aperitivo at its most textbook",
    verdictHook: "aperitivo",
  },
  "Canadian Club": {
    character: "grain-forward profile is wrong for scallops",
    verdictHook: "Canadian whisky",
  },
  "Caribou Crossing": {
    character: "craft profile is wrong for scallops",
    verdictHook: "Canadian whisky",
  },
  "Caymus Cabernet Sauvignon": {
    tastingNotes: ["Napa Rutherford Cab","concentrated black fruit","cocoa","mocha"],
    character: "cocoa-mocha-tannin weight is incoherent",
    verdictHook: "Napa Cab",
  },
  "Clase Azul Gold": {
    character: "joven blend with mezcal accent",
    verdictHook: "aged tequila",
  },
  "Clermont Steep": {
    character: "Jim Beam's wheated expression",
    verdictHook: "bourbon",
  },
  "Codigo 1530 Rosa": {
    character: "reposado aged in uncharred Napa Cabernet wine barrels",
    verdictHook: "reposado tequila",
  },
  "Corazon Reposado": {
    tastingNotes: ["Sazerac's tequila brand","single-estate highland agave"],
    verdictHook: "reposado tequila",
  },
  "Corazon Stagg": {
    character: "añejo tequila finished in ex-George-T",
    verdictHook: "aged tequila",
  },
  "Courvoisier Cognac": {
    tastingNotes: ["\"Napoleon's cognac","\" drier and oak-forward","traditional Jarnac producer"],
    character: "oak is over-specified but functional",
    verdictHook: "cognac",
  },
  "Crown Royal": {
    character: "vanilla-sweetness is wrong for scallops",
    verdictHook: "Canadian whisky",
  },
  "Daniel Chotard Sancerre Rouge": {
    character: "Loire Valley Pinot Noir",
    verdictHook: "elegant red",
  },
  "Darioush Cabernet Sauvignon": {
    tastingNotes: ["Silverado Trail Cab with blackcurrant","dark plum","mocha","spice"],
    verdictHook: "Napa Cab",
  },
  "Detroit City Gin": {
    character: "Detroit urban craft gin",
    verdictHook: "gin",
  },
  "Dewar's 15": {
    character: "15yr aged Highland blend",
    verdictHook: "scotch",
  },
  "Dewar's White Label": {
    character: "Highland blend with Aberfeldy-malt core",
    verdictHook: "scotch",
  },
  "Doc Swinson's Alter Ego Rye": {
    tastingNotes: ["craft sourced rye","Pacific Northwest boutique brand"],
    verdictHook: "rye whiskey",
  },
  "Don Fulano Anejo": {
    tastingNotes: ["Los Altos highland tequila","100% estate-grown Blue Weber"],
    verdictHook: "añejo tequila",
  },
  "Don Fulano Blanco": {
    tastingNotes: ["premium highland blanco","80 proof","refined craft"],
    verdictHook: "blanco tequila",
  },
  "Don Julio Reposado": {
    character: "reposado's agave and oak",
    verdictHook: "reposado tequila",
  },
  "Dunville's Single Malt": {
    character: "Belfast Irish single malt",
    verdictHook: "Irish whiskey",
  },
  "E.H. Taylor Rye": {
    character: "premium BIB BT rye",
    verdictHook: "rye whiskey",
  },
  "Eagle Rare 10 Year": {
    character: "aged oak and vanilla",
    verdictHook: "bourbon",
  },
  "El Mayor Extra Anejo": {
    character: "accessible aged El Mayor",
    verdictHook: "extra añejo tequila",
  },
  "El Mayor Reposado": {
    tastingNotes: ["value 80-proof reposado","agave-forward with light oak"],
    verdictHook: "reposado tequila",
  },
  "Elephant Gin": {
    character: "German craft African-botanical gin",
    verdictHook: "gin",
  },
  "Elijah Craig 18 Year": {
    tastingNotes: ["Heaven Hill aged single-barrel","tobacco","dried fruit)"],
    verdictHook: "bourbon",
  },
  "Elijah Craig Private Barrel": {
    character: "house-picked Heaven Hill single-barrel",
    verdictHook: "bourbon",
  },
  "Elijah Craig Straight Rye": {
    tastingNotes: ["Heaven Hill's 94-proof rye","sister to the Elijah Craig bourbon line"],
    verdictHook: "rye whiskey",
  },
  "Elk Cove Pinot Blanc": {
    tastingNotes: ["Willamette Oregon","soft pear","white peach","floral"],
    verdictHook: "Pinot Blanc",
  },
  "Elmer T. Lee": {
    tastingNotes: ["Buffalo Trace single-barrel","90 proof"],
    verdictHook: "single-barrel bourbon",
  },
  "Far Niente Cabernet Sauvignon": {
    tastingNotes: ["Oakville Cab with blackcurrant","dark chocolate","espresso","violet"],
    verdictHook: "Napa Cab",
  },
  "Far Niente Chardonnay": {
    tastingNotes: ["toasted hazelnut","crème brûlée","lush velvety texture"],
    character: "Napa flagship oak-cream-apple Chardonnay",
    verdictHook: "Chardonnay",
  },
  "Four Roses Yellow Label": {
    tastingNotes: ["floral","light-bodied entry bourbon"],
    verdictHook: "bourbon",
  },
  "Frangelico": {
    character: "Piedmont hazelnut depth to mocha at after-dinner register",
    verdictHook: "digestif liqueur",
  },
  "G.D. Vajra Moscato d'Asti": {
    character: "peach-and-honey frizzante sweetness cannot",
    verdictHook: "Moscato",
  },
  "Ghost Block Cabernet Sauvignon": {
    tastingNotes: ["Oakville Cab with dense blackcurrant","dark cherry","graphite","toasted oak"],
    verdictHook: "Napa Cab",
  },
  "Glenfiddich 12": {
    tastingNotes: ["entry Speyside benchmark","ex-bourbon-cask","apple/pear/honey gateway profile"],
    verdictHook: "Speyside scotch",
  },
  "Glenfiddich 18": {
    character: "Oloroso + bourbon cask",
    verdictHook: "Speyside scotch",
  },
  "Glenfiddich Gran Cru 23": {
    character: "Cuvée-finished 23-year Speyside luxury",
    verdictHook: "Speyside scotch",
  },
  "Glenmorangie 10": {
    tastingNotes: ["Highland entry benchmark","tallest stills in Scotland"],
    character: "honey-vanilla is a soft dessert finisher",
    verdictHook: "Highland scotch",
  },
  "Glenmorangie 18": {
    character: "aged bourbon + Oloroso Highland",
    verdictHook: "Highland scotch",
  },
  "Heaven's Door 10 Year": {
    character: "aged 10-year Dylan bourbon",
    verdictHook: "bourbon",
  },
  "Hennessy Cognac": {
    tastingNotes: ["ubiquitous VS/VSOP cognac","dried-fruit-and-vanilla benchmark"],
    character: "vanilla-and-oak marries cocoa cleanly",
    verdictHook: "cognac",
  },
  "Henry McKenna 10 Year Bottled in Bond": {
    character: "aged 100-proof bonded single-barrel",
    verdictHook: "bourbon",
  },
  "Inhibited": {
    character: "weight and chocolate drizzle",
    verdictHook: "spirit-forward cocktail",
  },
  "J. Davies Cabernet Sauvignon": {
    tastingNotes: ["graphite","mineral backbone","firm tannin"],
    verdictHook: "Napa Cab",
  },
  "Jack Daniel's 12 Year": {
    tastingNotes: ["aged Tennessee whiskey","12yr premium tier","deeper vanilla-caramel depth"],
    verdictHook: "scotch",
  },
  "Jean-Pierre Grossot Chablis": {
    tastingNotes: ["lemon","green apple"],
    verdictHook: "Chablis",
  },
  "Jefferson's Ocean Voyage 23": {
    tastingNotes: ["sea-aged bourbon","specific Voyage #23"],
    verdictHook: "bourbon",
  },
  "Jefferson's Reserve": {
    character: "blended honey and vanilla",
    verdictHook: "bourbon",
  },
  "Jefferson's Reserve VR Twin Oak": {
    character: "Twin Oak's double-barrel depth",
    verdictHook: "bourbon",
  },
  "Jim Beam Black Label": {
    tastingNotes: ["aged Jim Beam","8 years in the barrel","86 proof"],
    character: "aged Beam's oak and vanilla",
    verdictHook: "bourbon",
  },
  "Jordan Cabernet Sauvignon": {
    tastingNotes: ["Alexander Valley Cab with cassis","plum","cedar","mint"],
    character: "fine tannin makes it the fish-friendliest Cab",
    verdictHook: "Napa Cab",
  },
  "Joseph Mellot Sancerre": {
    tastingNotes: ["Loire Sauv Blanc with white grapefruit","chalk","fresh herbs","tension-filled finish"],
    verdictHook: "Sancerre",
  },
  "Keenan Chardonnay": {
    tastingNotes: ["Spring Mountain Napa with green apple","lemon curd","subtle oak","bright acidity"],
    character: "Spring Mountain oak-forward Napa Chardonnay",
    verdictHook: "Chardonnay",
  },
  "Kentucky Owl 10 Year Rye": {
    character: "Kentucky Owl's allocated 10-year premium rye",
    verdictHook: "rye whiskey",
  },
  "Knob Creek": {
    tastingNotes: ["100 proof","high-rye","nutty","full-bodied"],
    character: "nutty oak and high-rye spice",
    verdictHook: "bourbon",
  },
  "Knob Creek 12 Year": {
    character: "aged 12 years at 100 proof",
    verdictHook: "bourbon",
  },
  "Knob Creek Rye": {
    tastingNotes: ["Beam's 100-proof bold rye","sibling to Knob Creek Bourbon"],
    verdictHook: "rye whiskey",
  },
  "Lagavulin 8": {
    character: "peat smoke in the dram",
    verdictHook: "Islay scotch",
  },
  "Larceny Small Batch": {
    character: "Heaven Hill wheated caramel",
    verdictHook: "wheated bourbon",
  },
  "Le Garenne Rosé": {
    tastingNotes: ["Loire Pinot Noir with strawberry","watermelon","light floral","dry crisp"],
    verdictHook: "white wine",
  },
  "Little Book": {
    character: "Beam Little Book cask-strength",
    verdictHook: "bourbon",
  },
  "Loch Lomond 20 Year": {
    character: "complex 20yr aged Highland",
    verdictHook: "scotch",
  },
  "Lock Stock & Barrel Rye": {
    tastingNotes: ["sourced rye","often MGP-blended at premium age"],
    verdictHook: "rye whiskey",
  },
  "Louis XIII Cognac": {
    character: "40-100 year aged cognac",
    verdictHook: "icon cognac",
  },
  "Macallan 18": {
    character: "premium aged 18yr Speyside",
    verdictHook: "Speyside scotch",
  },
  "Macallan Estate": {
    character: "estate-oak character is distinctive",
    verdictHook: "Speyside scotch",
  },
  "Maker's Mark": {
    character: "soft caramel and vanilla",
    verdictHook: "wheated bourbon",
  },
  "Maker's Mark Cellar Aged": {
    character: "aged caramel and vanilla",
    verdictHook: "wheated bourbon",
  },
  "Mammoth 16 Year Single Barrel Rye": {
    character: "16-year aged Michigan rye",
    verdictHook: "rye whiskey",
  },
  "Michter's 10 Year Rye": {
    character: "10-year aged Michter's single-barrel",
    verdictHook: "rye whiskey",
  },
  "Michter's US*1 Rye": {
    character: "Michter's small-batch smooth rye",
    verdictHook: "rye whiskey",
  },
  "Milagro Anejo": {
    tastingNotes: ["Highland Jalisco 100% Blue Weber","triple-distilled"],
    verdictHook: "añejo tequila",
  },
  "New Holland Beer Barrel Bourbon": {
    character: "Holland MI beer-barrel finish",
    verdictHook: "bourbon",
  },
  "Oban 14": {
    character: "West Highland single malt",
    verdictHook: "Highland scotch",
  },
  "Oban 18": {
    tastingNotes: ["premium aged West Highland Oban","18yr with sherry-cask finish","deeper maritime-plus-sherry character"],
    character: "premium 18yr coastal Highland",
    verdictHook: "Highland scotch",
  },
  "Odette Cabernet Sauvignon": {
    tastingNotes: ["Stags Leap Cab","dark fruit","sage","cedar"],
    character: "Stags Leap Cab with iron-fist-in-a-velvet-glove quality",
    verdictHook: "Napa Cab",
  },
  "Old Emmer": {
    character: "wheated bourbon from emmer wheat",
    verdictHook: "bourbon",
  },
  "Old Fitzgerald 7 Year": {
    character: "Heaven Hill's wheated heritage bond",
    verdictHook: "wheated bourbon",
  },
  "Old Fitzgerald 9 Year": {
    character: "aged wheated BIB's mature honey",
    verdictHook: "wheated bourbon",
  },
  "Old Grand-Dad 16 Year": {
    character: "16yr OGD high-rye bourbon",
    verdictHook: "bourbon",
  },
  "Opus One": {
    tastingNotes: ["Oakville Bordeaux blend","dark fruit","mocha","cedar"],
    verdictHook: "Bordeaux blend",
  },
  "Our Lady of Guadalupe Acolytes": {
    tastingNotes: ["butterscotch","toasted oak","rich layered"],
    verdictHook: "white wine",
  },
  "Pappy Van Winkle 13 Year Rye": {
    character: "unicorn Van Winkle rye",
    verdictHook: "rye whiskey",
  },
  "Peju Cabernet Sauvignon": {
    tastingNotes: ["cassis","dusty cocoa","balanced acidity","refined tannin"],
    verdictHook: "Napa Cab",
  },
  "Pierre Ferrand Cognac": {
    tastingNotes: ["unblended vintage-style","traditional methods"],
    character: "Grande Champagne 1er Cru",
    verdictHook: "cognac",
  },
  "Pikesville Rye": {
    character: "110-proof HH Maryland-style rye",
    verdictHook: "rye whiskey",
  },
  "Pio Cesare Barbaresco": {
    character: "firm-tannin tar structure buries the delicate shellfish",
    verdictHook: "big red",
  },
  "Quilt Cabernet Sauvignon": {
    tastingNotes: ["Napa Cab with ripe blackberry","dark chocolate","toasted vanilla","soft polished tannin"],
    verdictHook: "Napa Cab",
  },
  "Robert Moncuit Les Grand Blancs": {
    tastingNotes: ["lemon curd","green apple","and no dosage"],
    character: "Le Mesnil Grand Cru Chardonnay",
    verdictHook: "sparkling",
  },
  "Ron Zacapa Rum": {
    tastingNotes: ["Guatemalan Solera 23","high-altitude Andean aging"],
    verdictHook: "heavy spirit",
  },
  "Russell's Reserve 10 Year": {
    character: "aged Wild Turkey oak",
    verdictHook: "bourbon",
  },
  "Sauternes Glass": {
    tastingNotes: ["apricot","honey","orange marmalade","luscious unctuous"],
    verdictHook: "dessert wine",
  },
  "Sazerac": {
    character: "rye weight and anise-edge",
    verdictHook: "spirit-forward cocktail",
  },
  "Scapegrace Fortuna": {
    character: "NZ craft single malt",
    verdictHook: "bourbon",
  },
  "Schloss Vollrads Riesling": {
    tastingNotes: ["Rheingau Riesling with apricot","white peach","petrol","lively acid"],
    character: "historic German Riesling estate",
    verdictHook: "Riesling",
  },
  "Silver Oak Cabernet Sauvignon": {
    tastingNotes: ["coconut","dill","ripe cassis","plum"],
    verdictHook: "Napa Cab",
  },
  "St Supéry Cabernet Sauvignon": {
    tastingNotes: ["Napa Rutherford Cab with blackberry","cassis","mocha","firm tannin"],
    verdictHook: "Napa Cab",
  },
  "St Supéry Sauvignon Blanc": {
    tastingNotes: ["Napa Dollarhide Sauv Blanc with lemon","grapefruit","gooseberry","clean lively"],
    verdictHook: "Sauvignon Blanc",
  },
  "Stagg Jr. Batch #15": {
    tastingNotes: ["BT non-age-statement cask-strength","premium batch"],
    character: "BT cask-strength batch #15",
    verdictHook: "cask-strength bourbon",
  },
  "Stoneleigh Sauvignon Blanc": {
    tastingNotes: ["grapefruit","grass","zesty"],
    verdictHook: "Sauvignon Blanc",
  },
  "Tears of Llorona": {
    tastingNotes: ["sherry","and cognac"],
    verdictHook: "aged tequila",
  },
  "Teeter Totter Cabernet Sauvignon": {
    tastingNotes: ["polished Napa Cab with rich dark fruit","mocha","smooth lingering finish","approachable concentration"],
    verdictHook: "Napa Cab",
  },
  "Thomas H. Handy Sazerac Rye": {
    tastingNotes: ["BTAC annual barrel-proof rye","uncut and unfiltered","from Buffalo Trace Antique Collection"],
    verdictHook: "rye whiskey",
  },
  "Trombo Cedano Reposado": {
    character: "aged in cedar-wood barrels",
    verdictHook: "reposado tequila",
  },
  "Veuve Clicquot Brut": {
    tastingNotes: ["Reims Champagne","ripe apple","white peach","biscuit"],
    verdictHook: "Champagne",
  },
  "Villon Cognac": {
    character: "modern profile and soft elderflower edge",
    verdictHook: "cognac",
  },
  "Weller 107": {
    character: "bigger-body wheated buries scallop sweetness",
    verdictHook: "wheated bourbon",
  },
  "Weller 12 Year": {
    character: "aged honey and oak",
    verdictHook: "wheated bourbon",
  },
  "Weller Millennium": {
    tastingNotes: ["20-year wheated bourbon","heavily allocated","the white-whale of the Weller family"],
    character: "deep wheated honey and the Millennium's oak",
    verdictHook: "wheated bourbon",
  },
  "WhistlePig 12 Year Old World": {
    tastingNotes: ["12-year WP finished in Sauternes","Madeira","and Port casks"],
    verdictHook: "rye whiskey",
  },
  "WhistlePig 15 Year": {
    tastingNotes: ["WP's 15-year premium flagship","92 proof","Vermont oak barrel finish"],
    verdictHook: "rye whiskey",
  },
  "WhistlePig PiggyBack 6 Year": {
    character: "100-proof 6-year WP rye",
    verdictHook: "rye whiskey",
  },
  "Willett Pot Still Reserve": {
    character: "craft high-rye oak spice",
    verdictHook: "bourbon",
  },
  "Woodford Reserve": {
    character: "small-batch fruit and floral",
    verdictHook: "bourbon",
  },
  "Woodinville Rye": {
    character: "Washington State small-batch rye",
    verdictHook: "rye whiskey",
  },
};

module.exports = { BOTTLE_PROFILES_MINED };
