// AUTO-GENERATED by engine/mine_gold_corpus.js -- do not edit by hand.
const GOLD_CORPUS_MINED = {
  "BIG_RED|STEAK_LEAN": [
    {
      "template": "Peak entry Napa Cab for filet — reliable Rutherford-style character for guests building confidence in the bottle pour.",
      "source": "1881 Napa Valley|Filet Mignon"
    },
    {
      "template": "Peak luxurious Cab for bone-in filet — Far Niente's long finish aligns with the premium tenderloin cut.",
      "source": "Bone-In Filet|Far Niente Cabernet Sauvignon"
    },
    {
      "template": "Peak elegant Cab for bone-in filet — Jordan's decades of consistency and balance align perfectly with the premium tenderloin cut.",
      "source": "Bone-In Filet|Jordan Cabernet Sauvignon"
    },
    {
      "template": "Peak collector Napa blend for bone-in filet — Mondavi-Rothschild prestige for the elevated cut.",
      "source": "Bone-In Filet|Opus One"
    },
    {
      "template": "Peak classified Bordeaux for filet — 1855-Classification French on the delicate cut.",
      "source": "Château Batailley|Filet Mignon"
    },
    {
      "template": "Peak Pomerol for filet — plush Merlot on the delicate cut.",
      "source": "Château Gombaude-Guillot|Filet Mignon"
    },
    {
      "template": "Peak luxurious Oakville Cab for filet — pair with the best cuts.",
      "source": "Far Niente Cabernet Sauvignon|Filet Mignon"
    },
    {
      "template": "Peak classic Barolo for filet — G.D.",
      "source": "Filet Mignon|G.D. Vajra Albe Nebbiolo"
    },
    {
      "template": "Peak historic-house Cab for filet.",
      "source": "Filet Mignon|Heitz Trailside Vineyard"
    },
    {
      "template": "Peak mountain Cab for filet — Schramsberg provenance hook.",
      "source": "Filet Mignon|J. Davies Cabernet Sauvignon"
    },
    {
      "template": "Peak mountain Merlot-Cab for filet — worth explaining Mernet to curious guests.",
      "source": "Filet Mignon|Keenan Mernet"
    },
    {
      "template": "Peak historically-pedigreed Napa Cab for filet — Lail family story on the delicate cut.",
      "source": "Filet Mignon|Lail Vineyards Blueprint"
    },
    {
      "template": "Peak elegant Napa Cab for filet — family-estate restraint on the classic tenderloin cut.",
      "source": "Filet Mignon|Peju Cabernet Sauvignon"
    },
    {
      "template": "Peak serious-Barolo for filet — one of Barolo's greatest names on the delicate cut.",
      "source": "Filet Mignon|Poderi Aldo Conterno Nebbiolo"
    },
    {
      "template": "Peak lush Napa Cab for filet — crowd-pleasing by-the-bottle anchor on the classic cut.",
      "source": "Filet Mignon|Quilt Cabernet Sauvignon"
    },
    {
      "template": "Peak organic Napa Cab for filet — estate story on the delicate cut.",
      "source": "Filet Mignon|Spottswoode Lyndenhurst"
    },
    {
      "template": "Peak by-the-glass Cab for filet — classic Rutherford Cab character at an accessible price.",
      "source": "Filet Mignon|St Supéry Cabernet Sauvignon"
    },
    {
      "template": "Peak estate Meritage for filet — age-integrated Napa.",
      "source": "Filet Mignon|St Supéry Élu Meritage"
    }
  ],
  "BIG_RED|STEAK_BOLD": [
    {
      "template": "Peak entry Napa Cab for Kansas City — reliable step-up from by-the-glass for guests ready to commit.",
      "source": "1881 Napa Valley|Kansas City"
    },
    {
      "template": "Peak Paso Cab for Cowboy — maximum richness for the big ribeye.",
      "source": "Austin Hope Cabernet Sauvignon|Cowboy Ribeye"
    },
    {
      "template": "Peak Paso Cab for Kansas City — warmer-climate richness frames the strip with a different register than Napa.",
      "source": "Austin Hope Cabernet Sauvignon|Kansas City"
    },
    {
      "template": "Peak Patagonian-Malbec for ribeye — silky elegance on the marbled cut.",
      "source": "Bodega Noemia A Lisa|Cowboy Ribeye"
    },
    {
      "template": "Peak mountain Cab for Cowboy — serious food-driven structure.",
      "source": "Brandlin Estate Cabernet Sauvignon|Cowboy Ribeye"
    },
    {
      "template": "Peak mountain Cab for Tomahawk — Mount Veeder structure stands up to the biggest marbled steak on the menu.",
      "source": "Brandlin Estate Cabernet Sauvignon|The Tomahawk"
    },
    {
      "template": "Peak mountain Cab for Cowboy — compelling story, serious bottle.",
      "source": "Cade Cabernet Sauvignon|Cowboy Ribeye"
    },
    {
      "template": "Peak crowd-pleasing Napa Cab for Cowboy — the name sells itself.",
      "source": "Caymus Cabernet Sauvignon|Cowboy Ribeye"
    },
    {
      "template": "Peak Mendoza for ribeye — plush Malbec built for grilled marbling.",
      "source": "Corazón del Sol Malbec|Cowboy Ribeye"
    },
    {
      "template": "Peak cult-Bandol for ribeye — exceptional with Cowboy per the card's own call-out.",
      "source": "Cowboy Ribeye|Domaine Tempier Bandol"
    },
    {
      "template": "Peak Paso-Rhône for ribeye — Epoch's serious winemaking on the cut.",
      "source": "Cowboy Ribeye|Epoch Ingenuity"
    },
    {
      "template": "Peak Super Tuscan for the 22oz bone-in — Maremma Bordeaux-style structure lives for this cut.",
      "source": "Cowboy Ribeye|Fattoria Le Pupille Saffredi"
    },
    {
      "template": "Peak value Napa Cab for Cowboy — brooding structure handles fat-and-char with layered complexity at a fair price.",
      "source": "Cowboy Ribeye|Faust Napa Valley Cabernet"
    },
    {
      "template": "Peak Oakville Cab for Cowboy — consistent structure at fair price.",
      "source": "Cowboy Ribeye|Ghost Block Cabernet Sauvignon"
    },
    {
      "template": "Peak California-Zin for ribeye — bold Napa on the marbled cut.",
      "source": "Cowboy Ribeye|Ghost Block Zinfandel"
    },
    {
      "template": "Peak historically-significant Napa Cab for ribeye — Daniel Cuvée named for Robin Lail's father, Mondavi-Inglenook architect.",
      "source": "Cowboy Ribeye|Lail Vineyards Daniel Cuvée"
    },
    {
      "template": "Peak Gigondas for ribeye — old-vine intensity on the marbled cut.",
      "source": "Cowboy Ribeye|Les Pallières Raciné"
    },
    {
      "template": "Peak Petite-Sirah for ribeye — powerful Napa on the marbled cut.",
      "source": "Cowboy Ribeye|Macauley Petite Syrah"
    },
    {
      "template": "Peak celebrated-vineyard Cab for Cowboy.",
      "source": "Cowboy Ribeye|Macauley Stagecoach Vineyard"
    },
    {
      "template": "Peak prestige Oakville Cab for Cowboy — terroir specificity for the fatted ribeye.",
      "source": "Cowboy Ribeye|Nickel & Nickel Cabernet"
    },
    {
      "template": "Peak collector Napa Cab blend for ribeye — Bordeaux-style flagship on the American bold cut.",
      "source": "Cowboy Ribeye|Opus One"
    },
    {
      "template": "Peak biodynamic-Brunello for the ribeye — Sesti's elegance polishes bold char.",
      "source": "Cowboy Ribeye|Sesti Brunello di Montalcino"
    },
    {
      "template": "Peak Stags Leap Cab for ribeye — bridge-to-Hillside-Select on the bold cut.",
      "source": "Cowboy Ribeye|Shafer 1.5"
    },
    {
      "template": "Peak collector's Napa Cab for ribeye — Hillside Select extraordinary length on the bold cut.",
      "source": "Cowboy Ribeye|Shafer Hillside Select"
    },
    {
      "template": "Peak recognizable Cab for Cowboy — guests who know Cabernet know Silver Oak.",
      "source": "Cowboy Ribeye|Silver Oak Cabernet Sauvignon"
    },
    {
      "template": "Peak boutique Napa Cab for ribeye — Simon Family reserve-level option for guests who want less well-known but equally serious.",
      "source": "Cowboy Ribeye|Simon Family Estate Reserve"
    },
    {
      "template": "Peak mid-tier Napa Cab for Cowboy — polished concentration frames fat-and-char without the prestige-bottle price.",
      "source": "Cowboy Ribeye|Teeter Totter Cabernet Sauvignon"
    },
    {
      "template": "Peak Prisoner for ribeye — reliable familiar sell on the marbled cut.",
      "source": "Cowboy Ribeye|The Prisoner Red Blend"
    },
    {
      "template": "Peak Oakville flagship for ribeye — step above Silencieux in power and presence.",
      "source": "Cowboy Ribeye|Venge Family Reserve"
    },
    {
      "template": "Peak for the 22oz bone-in — bold Californian fruit handles ribeye intensity.",
      "source": "Cowboy Ribeye|Venge Scout's Honor"
    },
    {
      "template": "Peak winemaker's Napa Cab for ribeye — Venge precision on the bold cut.",
      "source": "Cowboy Ribeye|Venge Silencieux"
    },
    {
      "template": "Peak opulent Napa Cab for Kansas City — Persian-inspired estate story on the classic strip.",
      "source": "Darioush Cabernet Sauvignon|Kansas City"
    },
    {
      "template": "Peak Paso-Rhône for the strip — European-inspired winemaking.",
      "source": "Epoch Ingenuity|Kansas City"
    },
    {
      "template": "Peak value Napa Cab for Kansas City — structure plus layered complexity at this price tier.",
      "source": "Faust Napa Valley Cabernet|Kansas City"
    },
    {
      "template": "Peak Bosché Vineyard Cab for the strip — 1970-legacy Rutherford structure on the American cut.",
      "source": "Freemark Abbey Bosché|Kansas City"
    },
    {
      "template": "Peak classic Barolo for the strip — Vajra's range includes Moscato on our Bubbles list.",
      "source": "G.D. Vajra Albe Nebbiolo|Kansas City"
    },
    {
      "template": "Peak Oakville Cab for Kansas City — Napa's most consistent strip-producing AVA delivers on the classic cut.",
      "source": "Ghost Block Cabernet Sauvignon|Kansas City"
    },
    {
      "template": "Peak California-Zin for the strip — bold Napa on the American cut.",
      "source": "Ghost Block Zinfandel|Kansas City"
    },
    {
      "template": "Peak mountain Cab for Kansas City — Schramsberg provenance story plus high-elevation concentration on the strip.",
      "source": "J. Davies Cabernet Sauvignon|Kansas City"
    },
    {
      "template": "Peak elegant Cab for Kansas City — trusted name, decades of consistency, balanced structure on the classic strip.",
      "source": "Jordan Cabernet Sauvignon|Kansas City"
    },
    {
      "template": "Peak cult Napa for Tomahawk — treat with reverence on the grand cut.",
      "source": "Jubilation by Colgin|The Tomahawk"
    },
    {
      "template": "Peak historically-pedigreed Napa Cab for the strip — Robin Lail's Mondavi-Inglenook pedigree on the American cut.",
      "source": "Kansas City|Lail Vineyards Blueprint"
    },
    {
      "template": "Peak elegant Napa Cab for Kansas City.",
      "source": "Kansas City|Peju Cabernet Sauvignon"
    },
    {
      "template": "Peak serious-Barolo for the strip — Aldo Conterno prestige on the American cut.",
      "source": "Kansas City|Poderi Aldo Conterno Nebbiolo"
    },
    {
      "template": "Peak polished Napa Cab for Kansas City — indulgent anchor without committing to a prestige bottle.",
      "source": "Kansas City|Quilt Cabernet Sauvignon"
    },
    {
      "template": "Peak Paso value Bordeaux blend for the strip — solid full-body on the American steakhouse cut.",
      "source": "Kansas City|San Simeon Stormwatch"
    },
    {
      "template": "Peak by-the-glass Cab for the strip — accessible California value on the American cut.",
      "source": "Kansas City|Scotto Cellars The Lost Chapters"
    },
    {
      "template": "Peak Stags Leap Cab for the strip — Shafer opulence on the American cut.",
      "source": "Kansas City|Shafer 1.5"
    },
    {
      "template": "Peak organic Napa Cab for the strip — Spottswoode family story on the American cut.",
      "source": "Kansas City|Spottswoode Lyndenhurst"
    },
    {
      "template": "Peak by-the-glass Napa Cab for Kansas City — accessible price point for a classic steak-and-Cab pairing.",
      "source": "Kansas City|St Supéry Cabernet Sauvignon"
    },
    {
      "template": "Peak estate Meritage for the strip — age-integrated Napa Bordeaux-style on the American cut.",
      "source": "Kansas City|St Supéry Élu Meritage"
    },
    {
      "template": "Peak mid-tier Napa Cab for Kansas City — crowd-pleaser balance without committing to a prestige bottle.",
      "source": "Kansas City|Teeter Totter Cabernet Sauvignon"
    },
    {
      "template": "Peak Prisoner for the strip — one of the country's most recognized labels.",
      "source": "Kansas City|The Prisoner Red Blend"
    },
    {
      "template": "Peak winemaker's Napa Cab for the strip — Venge precision on the American cut.",
      "source": "Kansas City|Venge Silencieux"
    },
    {
      "template": "Peak historically-significant Napa Cab for Tomahawk — Daniel Cuvée pedigree on the grand cut.",
      "source": "Lail Vineyards Daniel Cuvée|The Tomahawk"
    },
    {
      "template": "Peak Petite-Sirah — exceptional with Tomahawk per the card's call-out.",
      "source": "Macauley Petite Syrah|The Tomahawk"
    },
    {
      "template": "Peak celebrated-vineyard Cab for Tomahawk — Stagecoach's extreme diurnal shift gives structure to meet the biggest marbled steak.",
      "source": "Macauley Stagecoach Vineyard|The Tomahawk"
    },
    {
      "template": "Peak prestige Oakville Cab for Tomahawk — Nickel & Nickel's terroir-specific concentration stands up to the biggest marbled steak.",
      "source": "Nickel & Nickel Cabernet|The Tomahawk"
    },
    {
      "template": "Peak Napa prestige wine for Tomahawk — sell the collaboration story with the cut.",
      "source": "Opus One|The Tomahawk"
    },
    {
      "template": "Peak King-of-Italian for Tomahawk — Scavino prestige on the grand cut, demands the beef.",
      "source": "Scavino Barolo|The Tomahawk"
    },
    {
      "template": "Peak boutique Napa Cab for Tomahawk — Simon Family estate-grown fruit and reserve-level winemaking on the grand cut.",
      "source": "Simon Family Estate Reserve|The Tomahawk"
    },
    {
      "template": "Peak Oakville flagship for Tomahawk — Venge craftsman pedigree on the grand cut.",
      "source": "The Tomahawk|Venge Family Reserve"
    }
  ],
  "WHITE_WINE|CHICKEN_MAIN": [
    {
      "template": "Peak accessible Chardonnay for chicken across most seasonal preparations.",
      "source": "Alexander Valley Chardonnay|Roast Half Chicken"
    },
    {
      "template": "Peak Napa Chardonnay for chicken across most seasonal accompaniments.",
      "source": "Keenan Chardonnay|Roast Half Chicken"
    },
    {
      "template": "Peak provenance-forward Chardonnay for chicken across most seasonal builds.",
      "source": "Our Lady of Guadalupe Acolytes|Roast Half Chicken"
    }
  ],
  "ELEGANT_RED|STEAK_BOLD": [
    {
      "template": "Peak crowd-pleaser Bordeaux blend for the strip — accessible Sonoma red on the American cut.",
      "source": "Alexander Valley Homestead Red|Kansas City"
    },
    {
      "template": "Peak benchmark Barbera for the strip — Italian alternative to Barolo on the American cut.",
      "source": "Braida Montebruna Barbera|Kansas City"
    },
    {
      "template": "Peak right-bank Bordeaux for the strip — Grand Cru Merlot-led on the American steakhouse cut.",
      "source": "Château Haut Segottes|Kansas City"
    },
    {
      "template": "Peak left-bank Bordeaux for the strip — French classic on the American steakhouse cut.",
      "source": "Château de Rouillac|Kansas City"
    },
    {
      "template": "Peak rare-Napa CF for the strip — Darioush Persian-influenced estate on the American cut.",
      "source": "Darioush Cabernet Franc|Kansas City"
    },
    {
      "template": "Peak Anderson Valley Pinot for the strip — concentrated Mendocino red structured enough for the marbled cut.",
      "source": "J Davies Ferrington Vineyards|Kansas City"
    },
    {
      "template": "Peak Italian-approachable red for the strip — great value on the American cut.",
      "source": "Kansas City|Lunaria Coste di Moro"
    },
    {
      "template": "Peak accessible Pinot for the strip when guest wants lighter red pick.",
      "source": "Kansas City|Macauley Pinot Noir"
    },
    {
      "template": "Peak Rioja for the strip — oak-driven Tempranillo match.",
      "source": "Kansas City|Muga Reserva"
    }
  ],
  "ELEGANT_RED|CHICKEN_MAIN": [
    {
      "template": "Peak crowd-pleaser Bordeaux blend for chicken across most seasonal preparations.",
      "source": "Alexander Valley Homestead Red|Roast Half Chicken"
    },
    {
      "template": "Peak Italian-food-wine for chicken across most seasonal preparations.",
      "source": "Braida Montebruna Barbera|Roast Half Chicken"
    },
    {
      "template": "Peak Southern-French for the bird — preparation changes seasonally, check with kitchen for today's build.",
      "source": "Clos Petit Ona Grenache|Roast Half Chicken"
    },
    {
      "template": "Peak benchmark Oregon Pinot for chicken across most seasonal builds.",
      "source": "Cristom Mt Jefferson Cuvée|Roast Half Chicken"
    },
    {
      "template": "Peak Galician-Mencía for the bird — preparation changes seasonally, check with kitchen for today's build.",
      "source": "Fento Ollo de Sapo Mencía|Roast Half Chicken"
    },
    {
      "template": "Peak California Pinot for chicken — silky red across most seasonal preparations.",
      "source": "Fisher Unity Pinot Noir|Roast Half Chicken"
    },
    {
      "template": "Peak food wine for chicken — Chinon across most seasonal preparations.",
      "source": "Marc Brédif Chinon|Roast Half Chicken"
    },
    {
      "template": "Peak Rioja for the bird — preparation changes seasonally, check with kitchen for today's build.",
      "source": "Muga Reserva|Roast Half Chicken"
    }
  ],
  "LIGHT_SPIRIT|HEARTY_SOUP": [
    {
      "template": "Gold standard; the light-spirit-on-hearty-soup lock that sells itself.",
      "source": "Bacardi Rum|Shrimp Bisque"
    }
  ],
  "SWEET_LIQUEUR|DESSERT_CHOCOLATE": [
    {
      "template": "Gold standard; recommend the digestif-on-dessert pairing without hesitation.",
      "source": "Baileys Irish Cream|Chocolate Cake"
    },
    {
      "template": "Gold standard; this is the digestif-on-dessert call you put in front of every table.",
      "source": "Disaronno|Peanut Butter Brownie"
    },
    {
      "template": "Gold standard; the digestif-on-dessert pairing the menu was built around.",
      "source": "Frangelico|Peanut Butter Brownie"
    }
  ],
  "SWEET_LIQUEUR|DESSERT_LIGHT": [
    {
      "template": "Gold standard; this is the digestif-on-dessert match guests remember.",
      "source": "Beignets|Kahlua"
    },
    {
      "template": "Gold standard; the unskippable digestif-on-dessert pour.",
      "source": "Cheesecake|Disaronno"
    }
  ],
  "ELEGANT_RED|STEAK_LEAN": [
    {
      "template": "Peak serious Willamette Pinot for bone-in filet — structured enough for the elevated filet.",
      "source": "Bone-In Filet|Evening Land Seven Springs"
    },
    {
      "template": "Peak right-bank Bordeaux for filet — Grand Cru Merlot on the delicate cut.",
      "source": "Château Haut Segottes|Filet Mignon"
    },
    {
      "template": "Peak left-bank Bordeaux for filet — classified French classic for the delicate cut.",
      "source": "Château de Rouillac|Filet Mignon"
    },
    {
      "template": "Peak benchmark Pinot for filet — Willamette terroir frames the delicate cut.",
      "source": "Cristom Mt Jefferson Cuvée|Filet Mignon"
    },
    {
      "template": "Peak rare-Napa CF for filet — Persian-influenced estate story worth telling on the delicate cut.",
      "source": "Darioush Cabernet Franc|Filet Mignon"
    },
    {
      "template": "Peak flagship Willamette Pinot for filet — Domaine Serene elegance.",
      "source": "Domaine Serene Grand Cheval|Filet Mignon"
    },
    {
      "template": "Peak savory Willamette Pinot for filet — age-worthy Oregon serious red.",
      "source": "Evening Land Seven Springs|Filet Mignon"
    },
    {
      "template": "Peak Anderson Valley Pinot for filet — concentrated Mendocino red on the delicate cut.",
      "source": "Filet Mignon|J Davies Ferrington Vineyards"
    },
    {
      "template": "Peak food-friendly Pinot for filet — reliable Russian River on the delicate cut.",
      "source": "Filet Mignon|Jax Calesa Vineyard Pinot Noir"
    },
    {
      "template": "Peak Italian-approachable red for filet — great value on the delicate cut, Italian alternative to Cab.",
      "source": "Filet Mignon|Lunaria Coste di Moro"
    },
    {
      "template": "Peak accessible Pinot for filet — Macauley light body on the delicate cut at mid-tier price.",
      "source": "Filet Mignon|Macauley Pinot Noir"
    },
    {
      "template": "Peak plush California Pinot for filet — opulent Russian River style for the delicate cut.",
      "source": "Filet Mignon|Marimar Estate Christina"
    },
    {
      "template": "Peak Burgundian-style California Pinot for filet — one of California's finest.",
      "source": "Filet Mignon|RAEN Royal St Robert"
    },
    {
      "template": "Peak legendary-vineyard Pinot for filet — California Pinot history on the cut.",
      "source": "Filet Mignon|Sanford & Benedict Pinot Noir"
    },
    {
      "template": "Peak Tuscan Sangiovese for filet — Italian table wine on the delicate cut.",
      "source": "Filet Mignon|Tenuta di Arceno Chianti Classico"
    }
  ],
  "COCKTAIL_BOLD|STEAK_BOLD": [
    {
      "template": "Peak spirit-forward pour for the fattiest cut on the menu.",
      "source": "Bowdie's Old Fashioned|Cowboy Ribeye"
    },
    {
      "template": "Peak Manhattan pairing for the most approachable bold cut — weight-matches well.",
      "source": "Kansas City|The Manhattan"
    }
  ],
  "WHITE_WINE|LIGHT_SOUP": [
    {
      "template": "Peak balanced Chardonnay for broccoli cheddar — Napa structure on the classic.",
      "source": "Broccoli Cheddar|Keenan Chardonnay"
    },
    {
      "template": "Peak Riesling for butternut squash — textbook off-dry-on-sweet-vegetable pairing.",
      "source": "Butternut Squash|Schloss Vollrads Riesling"
    },
    {
      "template": "Peak special-occasion Chardonnay for creamy potato — Napa opulence on cream-on-cream.",
      "source": "Creamy Potato|Far Niente Chardonnay"
    }
  ],
  "TEQUILA_BOLD|HEARTY_STARTER": [
    {
      "template": "Gold standard; the unskippable añejo-on-rich-side pour.",
      "source": "Brussels and Belly|Corazon Weller"
    }
  ],
  "COCKTAIL_LIGHT|LIGHT_STARTER": [
    {
      "template": "Peak starter pairing — both lean into garden-fresh, clean profiles.",
      "source": "Burrata|Cucumber Gimlet"
    },
    {
      "template": "Peak classic cocktail for crab cake when guest wants citrus-forward agave.",
      "source": "Crab Cake|Margarita"
    }
  ],
  "SPARKLING|LIGHT_STARTER": [
    {
      "template": "Peak approachable opener for burrata.",
      "source": "Burrata|Il Colle Prosecco Superiore"
    },
    {
      "template": "Peak Champagne for crab cake — refined acidity frames the sweet shellfish perfectly.",
      "source": "Crab Cake|Laurent Perrier Le Cuvée Brut"
    },
    {
      "template": "Peak Cava for crab cake — sophisticated food-friendly pink at accessible price.",
      "source": "Crab Cake|Raventós Cava de NIT Rosé Brut"
    },
    {
      "template": "Peak reliable Champagne for crab cake — crowd-pleaser meets classic starter beautifully.",
      "source": "Crab Cake|Veuve Clicquot Brut"
    },
    {
      "template": "Peak sophisticated rosé Champagne for the seafood tower.",
      "source": "Laurent Perrier Brut Rosé|Seafood Tower"
    },
    {
      "template": "Peak seafood tower Champagne.",
      "source": "Laurent Perrier Le Cuvée Brut|Seafood Tower"
    },
    {
      "template": "Peak Champagne for shrimp cocktail — classical pairing at benchmark quality.",
      "source": "Laurent Perrier Le Cuvée Brut|Shrimp Cocktail"
    },
    {
      "template": "Peak grower rosé for the tower.",
      "source": "Paul Bara Grand Rosé Brut|Seafood Tower"
    },
    {
      "template": "Peak reliable Champagne for the tower.",
      "source": "Seafood Tower|Veuve Clicquot Brut"
    }
  ],
  "WHITE_WINE|LIGHT_STARTER": [
    {
      "template": "Peak pour.",
      "source": "Burrata|Le Garenne Rosé"
    },
    {
      "template": "Peak accessible NZ Sauv Blanc for burrata — reliable by-the-glass pairing.",
      "source": "Burrata|Stoneleigh Sauvignon Blanc"
    },
    {
      "template": "Peak serious Sauv Blanc for crab cake — more body than NZ expressions, more depth than Sancerre.",
      "source": "Crab Cake|Domaine de Berthiers Pouilly-Fumé"
    },
    {
      "template": "Peak benchmark Sauv Blanc for crab cake — Loire precision on the classic starter.",
      "source": "Crab Cake|Joseph Mellot Sancerre"
    }
  ],
  "SWEET_WINE|DESSERT_LIGHT": [
    {
      "template": "Peak heritage-Tawny for carrot cake — balanced spice match.",
      "source": "Carrot Cake|Taylor Fladgate Tawny"
    },
    {
      "template": "Peak Vin Santo for carrot cake — Tuscan-oxidative depth on the spiced bake.",
      "source": "Carrot Cake|Vin Santo"
    },
    {
      "template": "Peak Tawny for cheesecake — nutty-sweet match on the water-bath baked dessert.",
      "source": "Cheesecake|Graham's 10 Year Tawny"
    },
    {
      "template": "Peak heritage-Tawny for cheesecake — smooth balance handles the water-bath bake.",
      "source": "Cheesecake|Taylor Fladgate Tawny"
    },
    {
      "template": "Peak step-up Tawny for creme brulee — twenty years of cask evolution on the classic match.",
      "source": "Creme Brulee|Graham's 20 Year Tawny"
    }
  ],
  "SWEET_WINE|DESSERT_CHOCOLATE": [
    {
      "template": "Peak LBV for chocolate brownie — approachable port lineup on the dense bake.",
      "source": "Casa LBV Port|Chocolate Brownie"
    },
    {
      "template": "Peak Vintage Port for chocolate brownie — 2017 declared vintage meets cocoa intensity.",
      "source": "Chocolate Brownie|Graham's 2017 Vintage Port"
    },
    {
      "template": "Peak flagship-Vintage for chocolate brownie — Taylor's celebrated bottle on the dense bake.",
      "source": "Chocolate Brownie|Taylor Fladgate Vintage Bottle"
    },
    {
      "template": "Peak Vintage Port for chocolate cake — cocoa-on-cocoa with bottle-aged depth.",
      "source": "Chocolate Cake|Graham's 2017 Vintage Port"
    },
    {
      "template": "Peak flagship-Vintage for chocolate cake — cocoa-on-cocoa with evolving intensity.",
      "source": "Chocolate Cake|Taylor Fladgate Vintage Bottle"
    },
    {
      "template": "Peak step-up Tawny for peanut butter brownie — nut-on-nut complexity.",
      "source": "Graham's 20 Year Tawny|Peanut Butter Brownie"
    }
  ],
  "SPARKLING|DESSERT_LIGHT": [
    {
      "template": "Peak dessert-sparkling for our water-bath cheesecake's density.",
      "source": "Cheesecake|G.D. Vajra Moscato d'Asti"
    },
    {
      "template": "Peak dessert-sparkling pairing for the most approachable dessert on the menu.",
      "source": "Creme Brulee|G.D. Vajra Moscato d'Asti"
    }
  ],
  "WHITE_WINE|FISH_MAIN_RICH": [
    {
      "template": "Peak special-occasion Chardonnay for Chilean seabass — Napa opulence on the buttery classic.",
      "source": "Chilean Seabass|Far Niente Chardonnay"
    },
    {
      "template": "Peak balanced Chardonnay for Chilean seabass — Napa structure on the rich classic.",
      "source": "Chilean Seabass|Keenan Chardonnay"
    },
    {
      "template": "Peak special-occasion Chardonnay for swordfish — Napa opulence on the grilled classic.",
      "source": "Far Niente Chardonnay|Swordfish"
    },
    {
      "template": "Peak Oregon Chardonnay for salmon across most seasonal builds.",
      "source": "Faroe Island Salmon|Our Lady of Guadalupe Acolytes"
    }
  ],
  "COCKTAIL_BOLD|DESSERT_CHOCOLATE": [
    {
      "template": "Peak coffee-chocolate pairing — the espresso and coffee liqueur meet the dense fudge brownie's cocoa directly, and Averna's bitterness cuts the chocolate frosting's sweetness.",
      "source": "Chocolate Brownie|Espresso Martini"
    },
    {
      "template": "Peak dessert-cocktail pour — built for chocolate desserts.",
      "source": "Chocolate Brownie|Espresso Old Fashioned"
    },
    {
      "template": "Peak dessert cocktail when the cake returns; currently unavailable.",
      "source": "Chocolate Cake|Inhibited"
    },
    {
      "template": "Peak coffee-cocktail pour when the dessert returns; currently unavailable.",
      "source": "Espresso Martini|Mocha Creme"
    }
  ],
  "WHITE_WINE|HEARTY_SOUP": [
    {
      "template": "Peak balanced Chardonnay for clam chowder — Napa structure on the creamy classic.",
      "source": "Clam Chowder|Keenan Chardonnay"
    },
    {
      "template": "Peak special-occasion Chardonnay for bisque — Napa opulence on the cream starter.",
      "source": "Far Niente Chardonnay|Shrimp Bisque"
    }
  ],
  "ELEGANT_RED|FISH_MAIN_RICH": [
    {
      "template": "Peak Southern-French for salmon — preparation changes seasonally, check with kitchen for today's build.",
      "source": "Clos Petit Ona Grenache|Faroe Island Salmon"
    },
    {
      "template": "Peak Galician-Mencía for salmon — preparation changes seasonally, check with kitchen for today's build.",
      "source": "Faroe Island Salmon|Fento Ollo de Sapo Mencía"
    },
    {
      "template": "Peak reliable Pinot for salmon across most seasonal preparations.",
      "source": "Faroe Island Salmon|Jax Calesa Vineyard Pinot Noir"
    },
    {
      "template": "Peak food wine for salmon — lighter-than-Bordeaux CF handles fish across seasonal preparations.",
      "source": "Faroe Island Salmon|Marc Brédif Chinon"
    },
    {
      "template": "Peak plush Pinot for salmon — Russian River opulence across most preparations.",
      "source": "Faroe Island Salmon|Marimar Estate Christina"
    },
    {
      "template": "Peak legendary-vineyard Pinot for salmon — Santa Barbara depth across seasonal preparations.",
      "source": "Faroe Island Salmon|Sanford & Benedict Pinot Noir"
    }
  ],
  "TEQUILA_BOLD|STEAK_BOLD": [
    {
      "template": "Gold standard; recommend the añejo-on-bone-in-ribeye pairing without hesitation.",
      "source": "Corazon Stagg|The Tomahawk"
    }
  ],
  "BOURBON_BOLD|STEAK_BOLD": [
    {
      "template": "Gold standard; this is the bourbon-on-bone-in-ribeye pour the table writes home about.",
      "source": "Cowboy Ribeye|Macallan 18"
    },
    {
      "template": "Gold standard; the bourbon-on-bone-in-ribeye match that closes the table.",
      "source": "George T. Stagg|The Tomahawk"
    }
  ],
  "ELEGANT_RED|HEARTY_STARTER": [
    {
      "template": "Peak Loire red for escargot — French Pinot on the French classic.",
      "source": "Daniel Chotard Sancerre Rouge|Escargot"
    }
  ],
  "WHITE_WINE|FISH_MAIN_DELICATE": [
    {
      "template": "Peak Pinot Blanc for rainbow trout — Oregon white on the delicate classic.",
      "source": "Elk Cove Pinot Blanc|Rainbow Trout"
    },
    {
      "template": "Peak Chablis for rainbow trout — textbook Burgundian-on-freshwater-fish pairing.",
      "source": "Jean-Pierre Grossot Chablis|Rainbow Trout"
    },
    {
      "template": "Peak Chablis for salt-cured halibut — Burgundian precision on the cured classic.",
      "source": "Jean-Pierre Grossot Chablis|Salt-Cured Halibut"
    },
    {
      "template": "Peak textbook Chablis for scallops — unoaked precision on the French classic.",
      "source": "Jean-Pierre Grossot Chablis|Seared Scallops"
    },
    {
      "template": "Peak Chablis for tuxedo tuna — Burgundian precision on the crusted classic.",
      "source": "Jean-Pierre Grossot Chablis|Tuxedo-Crusted Yellowfin Tuna"
    },
    {
      "template": "Peak Sancerre for rainbow trout — Loire precision on the delicate classic.",
      "source": "Joseph Mellot Sancerre|Rainbow Trout"
    },
    {
      "template": "Peak Sancerre for scallops — textbook French-on-French pairing.",
      "source": "Joseph Mellot Sancerre|Seared Scallops"
    }
  ],
  "WHITE_WINE|CREAMY_SIDE": [
    {
      "template": "Peak special-occasion Chardonnay for the lobster mac side — indulgence-on-indulgence.",
      "source": "Far Niente Chardonnay|Lobster Mac"
    }
  ],
  "COCKTAIL_LIGHT|FISH_MAIN_DELICATE": [
    {
      "template": "Peak cocktail alternative to Champagne for scallops — shares the bubbles axis.",
      "source": "French 75|Seared Scallops"
    },
    {
      "template": "Peak floral-martini pairing for scallops — sophistication with approachability.",
      "source": "Lemon Lavender Gin Martini|Seared Scallops"
    }
  ],
  "WHITE_WINE|SALAD": [
    {
      "template": "Peak Napa Sauv Blanc for the wedge — rounded body reframes the classic, brightness keeps it fresh.",
      "source": "House Wedge|St Supéry Sauvignon Blanc"
    }
  ],
  "MEZCAL|RICH_SIDE": [
    {
      "template": "Gold standard; the mezcal-on-rich-side lock that sells itself.",
      "source": "Los Vecinos Mezcal|Mushrooms"
    }
  ],
  "COCKTAIL_BOLD|HEARTY_STARTER": [
    {
      "template": "Peak amaro-forward pre-dinner pairing for hand-cut beef — sophistication meets sophistication.",
      "source": "Not a Paper Plane|Prime Tartare"
    }
  ],
  "SPARKLING|HEARTY_STARTER": [
    {
      "template": "Peak prestige Champagne for tartare.",
      "source": "Pierre Gimonnet Special Club Brut|Prime Tartare"
    },
    {
      "template": "Peak occasion Champagne for tartare.",
      "source": "Pommery Cuvée Louise|Prime Tartare"
    }
  ],
  "SPARKLING|FISH_MAIN_DELICATE": [
    {
      "template": "Peak prestige Champagne for scallops.",
      "source": "Pierre Gimonnet Special Club Brut|Seared Scallops"
    },
    {
      "template": "Peak sommelier Champagne for scallops.",
      "source": "Robert Moncuit Les Grand Blancs|Seared Scallops"
    }
  ],
  "COCKTAIL_LIGHT|HEARTY_STARTER": [
    {
      "template": "Peak martini pairing for the hand-cut beef — sophistication matched.",
      "source": "Prime Tartare|Vesper"
    }
  ],
  "BIG_RED|CHICKEN_MAIN": [
    {
      "template": "Peak Paso value Bordeaux blend for chicken across most preparations.",
      "source": "Roast Half Chicken|San Simeon Stormwatch"
    },
    {
      "template": "Peak by-the-glass Cab for chicken across most seasonal preparations.",
      "source": "Roast Half Chicken|Scotto Cellars The Lost Chapters"
    }
  ]
};
module.exports = { GOLD_CORPUS_MINED };
