// Mines gold-tier verdicts from the preserved editorial portion of pairing-notes.js.
// EDITORIAL_PHRASES has 0 gold-tier entries; this fills that bucket.
'use strict';
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const taxonomy = require('./pairing_engine_taxonomy');

const repo = path.resolve(__dirname, '..');
const ctx = {}; vm.createContext(ctx);
const load = (f, n) => vm.runInContext(fs.readFileSync(path.join(repo, f), 'utf8') + '\nthis.' + n + ' = ' + n + ';', ctx);
load('pairing-map-v2.js','PAIRING_MAP');
load('pairing-notes.js','PAIRING_NOTES');

// Build gold-pairs lookup
const goldPairs = new Set();
for (const e of ctx.PAIRING_MAP) {
  if (Array.isArray(e.gold)) for (const g of e.gold) {
    goldPairs.add(e.name + '|' + g);
    goldPairs.add(g + '|' + e.name);
  }
}

// isTemplatedNote signatures (current engine output patterns)
function isTemplatedNote(note) {
  if (!note) return true;
  const sig = [
    /runs straight into/,
    /meets at register with/,
    /that defines /,
    /the call you don't second-guess/,
    /the call servers pour without second-guessing/,
    /reads cleanly at the table/,
    /reach for any of those/,
    /pick from the alternatives/,
    /elegance meets the plate/,
    /sits in the pocket on/,
    /earns a regular/,
    /dials in cleanly/,
    /workhorse pairing/,
    /keeps pace with/,
    /Save the .+ for the steak/,
    /Save the .+ for another course/,
    /belongs on (the steak|another) course/,
    /Hold the .+ for /,
    /that's the play/,
    /-- textbook\./,
    /the answer is /,
    /pour it and step back/,
    /if a guest asks what to drink with/,
    /is fine on .+ -- fine, not memorable/,
    /doesn't fight .+, but doesn't lift it either/,
    /pulls neither way against/,
    /backup when the strong calls/,
    /save the storytelling/,
    /spoken for/,
    /without asking for attention/,
    /is the answer, full stop/,
    /when a guest asks what works/,
  ];
  return sig.some(r => r.test(note));
}

// Extract verdict from a note: take the last sentence containing "Gold standard"
function extractGoldVerdict(note) {
  const sents = note.split(/(?<=[.!?])\s+/);
  for (const s of sents) {
    if (/gold standard/i.test(s) || /^Peak\b/i.test(s)) return s.trim();
  }
  return null;
}

const corpus = {};  // (drinkClass × foodClass) -> [{template, source}, ...]
const stats = { total: 0, templated: 0, editorial: 0, goldVerdictExtracted: 0 };

const notes = ctx.PAIRING_NOTES;
const byName = {}; for (const e of ctx.PAIRING_MAP) byName[e.name] = e;

for (const key of Object.keys(notes)) {
  const note = notes[key];
  if (!goldPairs.has(key)) continue;
  stats.total++;
  if (isTemplatedNote(note)) { stats.templated++; continue; }
  stats.editorial++;
  const v = extractGoldVerdict(note);
  if (!v) continue;
  stats.goldVerdictExtracted++;
  const [a, b] = key.split('|');
  const A = byName[a], B = byName[b]; if (!A || !B) continue;
  const drink = taxonomy.FOOD_CATS.has(A.category) ? B : A;
  const food  = taxonomy.FOOD_CATS.has(A.category) ? A : B;
  const dc = taxonomy.drinkClassFor(drink) || 'DEFAULT';
  const fc = taxonomy.foodClassFor(food)   || 'DEFAULT';
  const ck = dc + '|' + fc;
  if (!corpus[ck]) corpus[ck] = [];
  corpus[ck].push({ template: v, source: key });
}

// Dedupe by template text within each bucket
const out = {};
let totalEntries = 0;
for (const ck of Object.keys(corpus)) {
  const seen = new Set();
  out[ck] = [];
  for (const e of corpus[ck]) {
    const t = e.template;
    if (seen.has(t)) continue;
    seen.add(t);
    out[ck].push(e);
    totalEntries++;
  }
}

console.log('=== GOLD CORPUS MINING ===');
console.log('Gold pairs scanned:    ', stats.total);
console.log('Templated (skipped):   ', stats.templated);
console.log('Editorial (mined):     ', stats.editorial);
console.log('Gold verdicts extracted:', stats.goldVerdictExtracted);
console.log('Unique entries written:', totalEntries);
console.log('Unique (dc × fc) buckets:', Object.keys(out).length);
console.log('');
console.log('Top buckets by entry count:');
const buckets = Object.entries(out).sort((a,b) => b[1].length - a[1].length).slice(0, 12);
for (const [k, arr] of buckets) console.log('  '+k.padEnd(35)+arr.length);

// Write the file
const outPath = path.join(__dirname, 'gold_corpus_mined.js');
fs.writeFileSync(outPath,
  '// AUTO-GENERATED by engine/mine_gold_corpus.js -- do not edit by hand.\n' +
  'const GOLD_CORPUS_MINED = ' + JSON.stringify(out, null, 2) + ';\n' +
  'module.exports = { GOLD_CORPUS_MINED };\n'
);
console.log('\nWritten: '+outPath);
