// AUTO-GENERATED by engine/mine_tier_corrections_and_competitors.js
// TIER_CORRECTIONS: pairs where v9 verdict tier differs from pair-map tier.
// Format: "{Drink}|{Food}" -> tier (v9 actual)
const TIER_CORRECTIONS = {
  "Glenmorangie 10|Bone Marrow": "strong",
  "Glenmorangie 18|Bone Marrow": "strong",
  "Johnnie Walker Blue|Bone Marrow": "works",
};
module.exports = { TIER_CORRECTIONS };
